[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[context.production]
  environment = {
    NODE_ENV = "production"
  }

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
